[package]
name = "drive-core"
version = "0.1.0"
authors = ["david.bauske@googlemail.com"]

[dependencies]
i2cdev = "0.3.2"

serde = "1.0.29"
bincode = "1.0.0"
bufstream = "0.1.3"
ctrlc = "3.1.0"
rand = "0.4.2"

messages = { path = "../messages" }
util = { path = "../util" }
